### ISSUE TITLE
Make fastnick open source

### ISSUE THREAD

**Issue by SuperZekes** [Gizmo0oDev/FastNick-Issues#3]
I'd really like if you made the plugin open source so I could see whats going on with the code and thats really the point of a GitHub repo. Not just to upload the jar and the readme

**Comment by Gizmo0oDev** [comment]
The reason it's not open source is because it's a paid plugin on BuiltByBit, hope that answeres your question.

**Comment by SuperZekes** [comment]
You could make a GitHub repo for paying users to see (then I would want to buy it) because I think it would be cool if I could see how it works
