### ISSUE TITLE
Name above Head doesn‘t change

### ISSUE THREAD

**Issue by Schellti187** [Gizmo0oDev/FastNick-Issues#4]
Hello,

I just bought the FastNick Plugin an wanted to put it into my 1.21.1 Server. It worked almost perfect, but when I change the nickname, the name just changes in the TAB and the Chat, but not above the Players Head. That was the only reason I bought it for. It would be awasome if you could help me to solve this problem, so I can change the nick above the head. I also installed the other plugins and tried it in diffrent Minecraft Versions.

I would be really happy if you could answer me as quick as possible, couse I need it till today evenig.

Thank you in advance!

**Comment by Gizmo0oDev** [comment]
Have you installed the dependencies?

**Comment by Schellti187** [comment]
> Have you installed the dependencies?

Yes I did that. Everything works exept the Name above the head

**Comment by Gizmo0oDev** [comment]
Could you share your logs?
